"""empty message

Revision ID: 78a685e3dfdf
Revises: 8550d3f54e0b
Create Date: 2025-07-16 21:33:04.690206

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78a685e3dfdf'
down_revision = '8550d3f54e0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.alter_column('academic_grade_prof',
               existing_type=postgresql.ENUM('licenciatura', 'especialidad', 'maestria', 'doctorado', 'pos_doctorado', name='academicgradeprof'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.alter_column('academic_grade_prof',
               existing_type=postgresql.ENUM('licenciatura', 'especialidad', 'maestria', 'doctorado', 'pos_doctorado', name='academicgradeprof'),
               nullable=False)

    # ### end Alembic commands ###
