"""empty message

Revision ID: 8550d3f54e0b
Revises: 5755ee81f8c9
Create Date: 2025-07-10 19:32:31.431226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8550d3f54e0b'
down_revision = '5755ee81f8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.drop_column('academic_grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_grade', postgresql.ENUM('licenciatura', 'especialidad', 'maestria', 'doctorado', 'pos_doctorado', name='academicgradeprof'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
